### ISSUE TITLE
Unable to install hubot-wolfram

### ISSUE THREAD

**Issue by peterdalydickson** [notpeter/hubot-wolfram#3]
I've recently installed a new hubot, but got the following when I attempted to `npm install --save hubot-wolfram`...

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/jarvis/node_modules/libxmljs
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
jarvis@0.0.0 /opt/jarvis
└── hubot-rocketchat@0.1.1 

npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "hubot-wolfram"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/jarvis/npm-debug.log
```

Is this an issue with hubot-wolfram?

**Comment by notpeter** [comment]
Works fine for me on Ubuntu14.  What OS are you running? Do you have compilers, etc installed (`apt-get install build-essential`)? node-gyp depends on libxml which needs to be compiled.

**Comment by anishathalye** [comment]
The version of libxmljs this package is using (0.14, via `wolfram`) doesn't work with node 6.x. Version 0.18 should work.

Someone submitted a PR to wolfram (https://github.com/strax/node-wolfram/pull/18) , but I'm not sure if the package is still being maintained.

**Comment by notpeter** [comment]
Thanks for the link @anishathalye. I'll see if I can take crack and fixing this up.

**Comment by notpeter** [comment]
I forked strax/node-wolfram, applied strax/node-wolfram#18 and strax/node-wolfram#19 and published it on npm as [node-wolfram-api](https://www.npmjs.com/package/node-wolfram-api). 

Changes: [strax/node-wolfram vs notpeter/node-wolfram-api](https://github.com/strax/node-wolfram/compare/fc5c87d067770b7f5edd2c2252ef7cf6f2d0a302...notpeter:5dbcb39344f40cacbfefab1c0845dd9bac48380f)

Please let me know if just bumping your dependency to hubot-wolfram 1.1.0 is enough or if you need additional changes.

**Comment by anishathalye** [comment]
It's working for me. Thanks!

**Comment by anishathalye** [comment]
Oh, by the way, at least for me, this doesn't seem to be working with Node.js v4. It's working with Node.js v6 though.
